# Generated by Django 2.2.24 on 2021-10-30 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Polygon')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ('-created',),
            },
        ),
    ]
